feat(settings): add set-setting script and enhance get-setting
Adds a new `set-setting` script for managing script configurations.
Enhances the `get-setting` script to support retrieving specific key-value pairs
in addition to listing all settings. The `get-settings` script has been renamed
to `get-setting`.

diff --git a/get-setting b/get-setting
--- a/get-setting
+++ b/get-setting
@@ -12,35 +12,55 @@ source "${SCRIPT_DIR}/bash_modules/settings.sh"
 
 function print_usage() {
   cat <<EOF
-Usage: $(basename "$0")
+Usage: $(basename "$0") [key]
 
-Lists the script settings in a user-friendly format.
+Lists all script settings or returns a specific key/value pair.
 
 Dependencies:
   rg                 RipGrep recursively searches directories for a regex pattern
-  sed                Stream editor for filtering and transforming text
 
 Optional arguments:
+  key                The specific setting key to retrieve
   -h, --help         Show this help message and exit
 EOF
 }
 
-if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
+if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
   print_usage
-  exit 0
+  exit 1
 fi
 
 # Dependency Checks
 # -----------------------------------------------------------------------------
-dependencies=(rg sed)
+dependencies=(rg)
 for cmd in "${dependencies[@]}"; do
-    if ! command -v "${cmd}" >/dev/null; then
-        log_error "ERROR: Missing dependency - '${cmd}'"
-        exit 1
-    fi
+  if ! command -v "${cmd}" >/dev/null; then
+    log_error "ERROR: Missing dependency - '${cmd}'"
+    exit 1
+  fi
 done
 
-log_title "Get Script Settings"
-log_message "Settings file: $(settings_get_path)"
+# Main Logic
+# -----------------------------------------------------------------------------
+log_title "Get Script Setting"
+log_message "Source: $(settings_get_path)"
+
+declare key="${1}"
+
+if [[ -n "${key}" ]]; then
+  declare value
+  value="$(settings_get "${key}")"
+
+  if [[ -n "${value}" ]]; then
+    log_newline
+    printf '%s="%s"\n' "${key}" "${value}"
+    exit 0
+  fi
+
+  log_error "Key '${key}' not found in settings"
+  exit 1
+fi
+
+log_message "Listing all settings:"
 log_newline
 settings_list
